### ISSUE TITLE
KOK ADA LOGGERNYA? 

### ISSUE THREAD

**Issue by Isallkun** [rezadkim/dark-fb#4]
hehehehe, numpang ngancurin lapak tapi ya kalau gua udah beli lisensi kok masih ada LOGGERNYA kan dosa gitu ¬_¬

**Comment by ertz1** [comment]
Adakah?

**Comment by buyuang-biaro** [comment]
Maksud nya apa Gan ?
Gw kagak pernah coment atau apapun yg nyinggung dark-fb
Gw juga make tool itu soalnya
Jadi penasaran gw

Pada tanggal 12 Jun 2019 1.58 PM, "ertz1" <notifications@github.com>
menulis:

**Comment by ertz1** [comment]
Coba Ss Gan:v Takut Lupa Gw/Fb Gw Ada Yg Hack

Pada tanggal Rab, 12 Jun 2019 15.06, buyuang-biaro <notifications@github.com>
menulis:

**Comment by MuhShalah007** [comment]
boleh minta penjelasannya bang @SantriInsyaf?
saya selaku peneliti Dark-Fbnya bang @rezadkim ingin menyakannya.

**Comment by Isallkun** [comment]
> boleh minta penjelasannya bang @SantriInsyaf?
> saya selaku peneliti Dark-Fbnya bang @rezadkim ingin menyakannya.

Bjir gue dah lupa setahun yang lalu soalnya, terus ada yang open mind di termux indo sebelumnya tapi dah tenggelam klo sekarang

**Comment by ADustyCode** [comment]
Palingan versi recode yg di kasi logger

**Comment by Isallkun** [comment]
Dahlah gan close aja, gw dah lupa
